var sentences = {
    levels: [
        {
            level: 1,
            name: "רמה 1: יסודות",
            sentences: [
                { text: "El perro es ____.", missing: "grande", choices: ["grande", "rojo", "come"] },
                { text: "Yo bebo ____.", missing: "agua", choices: ["agua", "hablo", "gato"] },
                { text: "La mujer ____ un libro.", missing: "lee", choices: ["lee", "corre", "manzana"] },
                { text: "El hombre tiene un ____.", missing: "coche", choices: ["coche", "casa", "hola"] },
                { text: "El ____ es azul.", missing: "cielo", choices: ["cielo", "sol", "luna"] },
                { text: "____, ¿cómo estás?", missing: "Hola", choices: ["Hola", "Adiós", "Gracias"] },
                { text: "La casa es ____.", missing: "blanca", choices: ["blanca", "negro", "amarillo"] },
                { text: "Mi ____ se llama Juan.", missing: "amigo", choices: ["amigo", "hermana", "madre"] },
                { text: "Quiero ____, por favor.", missing: "café", choices: ["café", "leche", "vino"] },
                { text: "El número ____ es mi favorito.", missing: "siete", choices: ["siete", "ocho", "nueve"] },
                { text: "No me gusta el color ____.", missing: "verde", choices: ["verde", "rojo", "azul"] },
                { text: "El ____ es un animal grande.", missing: "elefante", choices: ["elefante", "ratón", "pájaro"] },
                { text: "Necesito ____ para mi coche.", missing: "llaves", choices: ["llaves", "puerta", "ventana"] },
                { text: "Ella ____ muy bien.", missing: "canta", choices: ["canta", "baila", "escribe"] },
                { text: "El ____ es muy alto.", missing: "árbol", choices: ["árbol", "flor", "río"] },
                { text: "Hoy es un ____ bonito.", missing: "día", choices: ["día", "noche", "tarde"] },
                { text: "Mi ____ es azul.", missing: "coche", choices: ["coche", "casa", "perro"] },
                { text: "La ____ es mi fruta favorita.", missing: "manzana", choices: ["manzana", "plátano", "naranja"] },
                { text: "Yo ____ en una ciudad grande.", missing: "vivo", choices: ["vivo", "trabajo", "como"] },
                { text: "El ____ es un animal doméstico.", missing: "gato", choices: ["gato", "león", "tigre"] },
                { text: "____ a la playa en verano.", missing: "Voy", choices: ["Voy", "Fui", "Iré"] },
                { text: "Mi padre es ____.", missing: "alto", choices: ["alto", "bajo", "delgado"] },
                { text: "La ____ es muy importante.", missing: "familia", choices: ["familia", "escuela", "fiesta"] },
                { text: "Me gusta ____ música.", missing: "escuchar", choices: ["escuchar", "ver", "leer"] },
                { text: "El ____ es mi bebida favorita.", missing: "café", choices: ["café", "té", "jugo"] }
            ]
        },
        {
            level: 2,
            name: "רמה 2: מילות יחס",
            sentences: [
                { text: "El gato está ____ la mesa.", missing: "sobre", choices: ["sobre", "con", "y"] },
                { text: "El libro es ____ ti.", missing: "para", choices: ["para", "sin", "él"] },
                { text: "Voy a la playa ____ mi amigo.", missing: "con", choices: ["con", "desde", "hasta"] },
                { text: "La casa está ____ del parque.", missing: "cerca", choices: ["cerca", "lejos", "entre"] },
                { text: "Camino ____ la calle.", missing: "por", choices: ["por", "a", "de"] },
                { text: "La comida está ____ el plato.", missing: "en", choices: ["en", "a", "de"] },
                { text: "El perro duerme ____ del árbol.", missing: "debajo", choices: ["debajo", "encima", "al lado"] },
                { text: "El coche está ____ de la casa.", missing: "delante", choices: ["delante", "detrás", "dentro"] },
                { text: "La tienda está ____ el banco y el cine.", missing: "entre", choices: ["entre", "sobre", "hacia"] },
                { text: "Voy ____ la escuela.", missing: "a", choices: ["a", "de", "en"] },
                { text: "Vengo ____ mi casa.", missing: "de", choices: ["de", "a", "con"] },
                { text: "El avión vuela ____ las nubes.", missing: "sobre", choices: ["sobre", "bajo", "a través de"] },
                { text: "Hablo ____ mi madre por teléfono.", missing: "con", choices: ["con", "para", "de"] },
                { text: "El regalo es ____ mi hermana.", missing: "para", choices: ["para", "de", "a"] },
                { text: "No puedo vivir ____ ti.", missing: "sin", choices: ["sin", "con", "para"] },
                { text: "El tren va ____ Madrid.", missing: "hacia", choices: ["hacia", "desde", "sin"] },
                { text: "Trabajo ____ las 9 ____ las 5.", missing: "desde...hasta", choices: ["desde...hasta", "a...de", "con...sin"] },
                { text: "El niño está ____ sus padres.", missing: "con", choices: ["con", "entre", "sobre"] },
                { text: "La pelota está ____ de la caja.", missing: "dentro", choices: ["dentro", "fuera", "al lado"] },
                { text: "La farmacia está ____ del hospital.", missing: "al lado", choices: ["al lado", "lejos", "detrás"] },
                { text: "El gato se escondió ____ la cama.", missing: "debajo", choices: ["debajo", "encima", "en"] },
                { text: "Voy a viajar ____ avión.", missing: "en", choices: ["en", "con", "a"] },
                { text: "El libro está ____ la estantería.", missing: "en", choices: ["en", "sobre", "debajo"] },
                { text: "La carta es ____ Juan.", missing: "de", choices: ["de", "para", "a"] },
                { text: "El perro corre ____ el gato.", missing: "detrás de", choices: ["detrás de", "delante de", "al lado de"] }
            ]
        },
        {
            level: 3,
            name: "רמה 3: זמנים",
            sentences: [
                { text: "Ayer, yo ____ una película.", missing: "vi", choices: ["vi", "veo", "veré"] },
                { text: "Mañana, nosotros ____ a la escuela.", missing: "iremos", choices: ["iremos", "fuimos", "vamos"] },
                { text: "Ahora, ella está ____.", missing: "comiendo", choices: ["comiendo", "comió", "comerá"] },
                { text: "Él ____ mucho todos los días.", missing: "trabaja", choices: ["trabaja", "trabajó", "trabajará"] },
                { text: "La semana pasada, ____ a mi abuela.", missing: "visité", choices: ["visité", "visito", "visitaré"] },
                { text: "En este momento, ____ lloviendo.", missing: "está", choices: ["está", "estuvo", "estará"] },
                { text: "El próximo año, ____ a Europa.", missing: "viajaré", choices: ["viajaré", "viajé", "viajo"] },
                { text: "Anoche, ____ muy tarde.", missing: "dormí", choices: ["dormí", "duermo", "dormiré"] },
                { text: "Normalmente, ____ a las 7 de la mañana.", missing: "me levanto", choices: ["me levanto", "me levanté", "me levantaré"] },
                { text: "Cuando era niño, ____ mucho.", missing: "jugaba", choices: ["jugaba", "juego", "jugaré"] },
                { text: "Si tuviera dinero, ____ un coche nuevo.", missing: "compraría", choices: ["compraría", "compro", "compraré"] },
                { text: "Él ____ en Madrid desde hace 5 años.", missing: "vive", choices: ["vive", "vivió", "vivirá"] },
                { text: "Mientras tú ____, yo estudiaba.", missing: "dormías", choices: ["dormías", "duermes", "dormirás"] },
                { text: "Cuando llegues, ____ la cena.", missing: "prepararé", choices: ["prepararé", "preparé", "preparo"] },
                { text: "Ayer ____ mucho frío.", missing: "hizo", choices: ["hizo", "hace", "hará"] },
                { text: "En 2010, ____ en la universidad.", missing: "estudiaba", choices: ["estudiaba", "estudio", "estudiaré"] },
                { text: "No ____ a la fiesta anoche.", missing: "fui", choices: ["fui", "voy", "iré"] },
                { text: "Ahora mismo, ____ escribiendo un correo.", missing: "estoy", choices: ["estoy", "estuve", "estaré"] },
                { text: "El mes que viene, ____ mi cumpleaños.", missing: "será", choices: ["será", "es", "fue"] },
                { text: "Cuando era joven, ____ la guitarra.", missing: "tocaba", choices: ["tocaba", "toco", "tocaré"] },
                { text: "Si llueve mañana, no ____.", missing: "saldré", choices: ["saldré", "salgo", "salí"] },
                { text: "Ayer, ____ un libro interesante.", missing: "leí", choices: ["leí", "leo", "leeré"] },
                { text: "En el futuro, la gente ____ en Marte.", missing: "vivirá", choices: ["vivirá", "vive", "vivió"] },
                { text: "Cuando llegué, ella ya se ____.", missing: "había ido", choices: ["había ido", "fue", "va"] },
                { text: "Espero que ____ un buen día.", missing: "tengas", choices: ["tengas", "tienes", "tuviste"] }
            ]
        }
    ]
};
