var words_de = {
    levels: [
        { level: 1, name: "רמה 1: Grundlagen", words: [ { hebrew: "שלום", foreign: "Hallo" }, { hebrew: "תודה", foreign: "Danke" }, { hebrew: "כן", foreign: "Ja" }, { hebrew: "לא", foreign: "Nein" }, { hebrew: "בבקשה", foreign: "Bitte" }, { hebrew: "להתראות", foreign: "Auf Wiedersehen" }, { hebrew: "סליחה", foreign: "Entschuldigung" } ] },
        { level: 2, name: "רמה 2: Leute", words: [ { hebrew: "איש", foreign: "Mann" }, { hebrew: "אישה", foreign: "Frau" }, { hebrew: "ילד", foreign: "Junge" }, { hebrew: "ילדה", foreign: "Mädchen" }, { hebrew: "חבר", foreign: "Freund" }, { hebrew: "משפחה", foreign: "Familie" }, { hebrew: "אבא", foreign: "Vater" } ] },
        { level: 3, name: "רמה 3: Zahlen", words: [ { hebrew: "אחת", foreign: "Eins" }, { hebrew: "שתיים", foreign: "Zwei" }, { hebrew: "שלוש", foreign: "Drei" }, { hebrew: "ארבע", foreign: "Vier" }, { hebrew: "חמש", foreign: "Fünf" }, { hebrew: "שש", foreign: "Sechs" }, { hebrew: "שבע", foreign: "Sieben" } ] },
        { level: 4, name: "רמה 4: Farben", words: [ { hebrew: "אדום", foreign: "Rot" }, { hebrew: "כחול", foreign: "Blau" }, { hebrew: "ירוק", foreign: "Grün" }, { hebrew: "צהוב", foreign: "Gelb" }, { hebrew: "שחור", foreign: "Schwarz" }, { hebrew: "לבן", foreign: "Weiß" }, { hebrew: "כתום", foreign: "Orange" } ] },
        { level: 5, name: "רמה 5: Tiere", words: [ { hebrew: "כלב", foreign: "Hund" }, { hebrew: "חתול", foreign: "Katze" }, { hebrew: "סוס", foreign: "Pferd" }, { hebrew: "דג", foreign: "Fisch" }, { hebrew: "ציפור", foreign: "Vogel" }, { hebrew: "אריה", foreign: "Löwe" }, { hebrew: "פרה", foreign: "Kuh" } ] },
        { level: 6, name: "רמה 6: Essen", words: [ { hebrew: "מים", foreign: "Wasser" }, { hebrew: "לחם", foreign: "Brot" }, { hebrew: "תפוח", foreign: "Apfel" }, { hebrew: "גבינה", foreign: "Käse" }, { hebrew: "חלב", foreign: "Milch" }, { hebrew: "אורז", foreign: "Reis" }, { hebrew: "עוף", foreign: "Huhn" } ] },
        { level: 7, name: "רמה 7: Verben", words: [ { hebrew: "ללכת", foreign: "Gehen" }, { hebrew: "לאכול", foreign: "Essen" }, { hebrew: "לשתות", foreign: "Trinken" }, { hebrew: "לראות", foreign: "Sehen" }, { hebrew: "לדבר", foreign: "Sprechen" }, { hebrew: "לקרוא", foreign: "Lesen" }, { hebrew: "לכתוב", foreign: "Schreiben" } ] },
        { level: 8, name: "רמה 8: Adjektive", words: [ { hebrew: "גדול", foreign: "Groß" }, { hebrew: "קטן", foreign: "Klein" }, { hebrew: "טוב", foreign: "Gut" }, { hebrew: "רע", foreign: "Schlecht" }, { hebrew: "שמח", foreign: "Glücklich" }, { hebrew: "עצוב", foreign: "Traurig" }, { hebrew: "חדש", foreign: "Neu" } ] },
        { level: 9, name: "רמה 9: Kleidung", words: [ { hebrew: "חולצה", foreign: "Hemd" }, { hebrew: "מכנסיים", foreign: "Hose" }, { hebrew: "נעליים", foreign: "Schuhe" }, { hebrew: "כובע", foreign: "Hut" }, { hebrew: "שמלה", foreign: "Kleid" }, { hebrew: "מעיל", foreign: "Mantel" }, { hebrew: "גרביים", foreign: "Socken" } ] },
        { level: 10, name: "רמה 10: Körper", words: [ { hebrew: "ראש", foreign: "Kopf" }, { hebrew: "יד", foreign: "Hand" }, { hebrew: "רגל", foreign: "Fuß" }, { hebrew: "עין", foreign: "Auge" }, { hebrew: "פה", foreign: "Mund" }, { hebrew: "אף", foreign: "Nase" }, { hebrew: "אוזן", foreign: "Ohr" } ] },
        { level: 11, name: "רמה 11: Haus", words: [ { hebrew: "בית", foreign: "Haus" }, { hebrew: "דלת", foreign: "Tür" }, { hebrew: "חלון", foreign: "Fenster" }, { hebrew: "מיטה", foreign: "Bett" }, { hebrew: "מטבח", foreign: "Küche" }, { hebrew: "שולחן", foreign: "Tisch" }, { hebrew: "כיסא", foreign: "Stuhl" } ] },
        { level: 12, name: "רמה 12: Stadt", words: [ { hebrew: "עיר", foreign: "Stadt" }, { hebrew: "מכונית", foreign: "Auto" }, { hebrew: "רחוב", foreign: "Straße" }, { hebrew: "חנות", foreign: "Geschäft" }, { hebrew: "בית ספר", foreign: "Schule" }, { hebrew: "בנק", foreign: "Bank" }, { hebrew: "גשר", foreign: "Brücke" } ] },
        { level: 13, name: "רמה 13: Reisen", words: [ { hebrew: "מטוס", foreign: "Flugzeug" }, { hebrew: "מלון", foreign: "Hotel" }, { hebrew: "רכבת", foreign: "Zug" }, { hebrew: "חוף", foreign: "Strand" }, { hebrew: "מפה", foreign: "Karte" }, { hebrew: "כרטיס", foreign: "Ticket" }, { hebrew: "מזוודה", foreign: "Koffer" } ] },
        { level: 14, name: "רמה 14: Natur", words: [ { hebrew: "שמש", foreign: "Sonne" }, { hebrew: "ירח", foreign: "Mond" }, { hebrew: "עץ", foreign: "Baum" }, { hebrew: "פרח", foreign: "Blume" }, { hebrew: "מים", foreign: "Wasser" }, { hebrew: "שמיים", foreign: "Himmel" }, { hebrew: "כוכב", foreign: "Stern" } ] },
        { level: 15, name: "רמה 15: Zeit", words: [ { hebrew: "יום", foreign: "Tag" }, { hebrew: "שנה", foreign: "Jahr" }, { hebrew: "שעה", foreign: "Stunde" }, { hebrew: "דקה", foreign: "Minute" }, { hebrew: "שבוע", foreign: "Woche" }, { hebrew: "היום", foreign: "Heute" }, { hebrew: "מחר", foreign: "Morgen" } ] }
    ]
};
