var words = {
    levels: [
        {
            level: 1,
            name: "רמה 1: יסודות",
            words: [
                { hebrew: "שלום", foreign: "Hola" },
                { hebrew: "להתראות", foreign: "Adiós" },
                { hebrew: "תודה", foreign: "Gracias" },
                { hebrew: "בבקשה", foreign: "Por favor" },
                { hebrew: "סליחה", foreign: "Perdón" },
                { hebrew: "כן", foreign: "Sí" },
                { hebrew: "לא", foreign: "No" },
                { hebrew: "אני", foreign: "yo" },
                { hebrew: "אתה", foreign: "tú" },
                { hebrew: "הוא", foreign: "él" },
                { hebrew: "היא", foreign: "ella" },
                { hebrew: "אנחנו", foreign: "nosotros" },
                { hebrew: "אתם", foreign: "vosotros" },
                { hebrew: "הם", foreign: "ellos" }
            ]
        },
        {
            level: 2,
            name: "רמה 2: אנשים ומשפחה",
            words: [
                { hebrew: "איש", foreign: "Hombre" },
                { hebrew: "אישה", foreign: "Mujer" },
                { hebrew: "ילד", foreign: "Niño" },
                { hebrew: "ילדה", foreign: "Niña" },
                { hebrew: "חבר", foreign: "Amigo" },
                { hebrew: "חברה", foreign: "Amiga" },
                { hebrew: "משפחה", foreign: "Familia" },
                { hebrew: "אבא", foreign: "padre" },
                { hebrew: "אמא", foreign: "madre" },
                { hebrew: "אח", foreign: "hermano" },
                { hebrew: "אחות", foreign: "hermana" },
                { hebrew: "בן", foreign: "hijo" },
                { hebrew: "בת", foreign: "hija" },
                { hebrew: "סבא", foreign: "abuelo" },
                { hebrew: "סבתא", foreign: "abuela" }
            ]
        },
        {
            level: 3,
            name: "רמה 3: מספרים",
            words: [
                { hebrew: "אחד", foreign: "uno" },
                { hebrew: "שתיים", foreign: "dos" },
                { hebrew: "שלוש", foreign: "tres" },
                { hebrew: "ארבע", foreign: "cuatro" },
                { hebrew: "חמש", foreign: "cinco" },
                { hebrew: "שש", foreign: "seis" },
                { hebrew: "שבע", foreign: "siete" },
                { hebrew: "שמונה", foreign: "ocho" },
                { hebrew: "תשע", foreign: "nueve" },
                { hebrew: "עשר", foreign: "diez" }
            ]
        },
        {
            level: 4,
            name: "רמה 4: צבעים",
            words: [
                { hebrew: "אדום", foreign: "rojo" },
                { hebrew: "כחול", foreign: "azul" },
                { hebrew: "ירוק", foreign: "verde" },
                { hebrew: "צהוב", foreign: "amarillo" },
                { hebrew: "שחור", foreign: "negro" },
                { hebrew: "לבן", foreign: "blanco" },
                { hebrew: "כתום", foreign: "naranja" },
                { hebrew: "סגול", foreign: "morado" },
                { hebrew: "ורוד", foreign: "rosa" },
                { hebrew: "חום", foreign: "marrón" }
            ]
        },
        {
            level: 5,
            name: "רמה 5: חיות",
            words: [
                { hebrew: "כלב", foreign: "perro" },
                { hebrew: "חתול", foreign: "gato" },
                { hebrew: "ציפור", foreign: "pájaro" },
                { hebrew: "סוס", foreign: "caballo" },
                { hebrew: "פרה", foreign: "vaca" },
                { hebrew: "כבשה", foreign: "oveja" },
                { hebrew: "חזיר", foreign: "cerdo" },
                { hebrew: "תרנגול", foreign: "gallina" },
                { hebrew: "דב", foreign: "oso" },
                { hebrew: "ארנב", foreign: "conejo" },
                { hebrew: "עכבר", foreign: "ratón" },
                { hebrew: "חמור", foreign: "burro" },
                { hebrew: "גמל", foreign: "camello" },
                { hebrew: "זאב", foreign: "lobo" },
                { hebrew: "שועל", foreign: "zorro" },
                { hebrew: "נמר", foreign: "tigre" },
                { hebrew: "פיל", foreign: "elefante" },
                { hebrew: "קוף", foreign: "mono" },
                { hebrew: "צבי", foreign: "ciervo" },
                { hebrew: "לטאה", foreign: "lagarto" },
                { hebrew: "נחש", foreign: "serpiente" },
                { hebrew: "צב", foreign: "tortuga" },
                { hebrew: "כריש", foreign: "tiburón" },
                { hebrew: "לוויתן", foreign: "ballena" },
                { hebrew: "דולפין", foreign: "delfín" },
                { hebrew: "עכביש", foreign: "araña" },
                { hebrew: "נמלה", foreign: "hormiga" },
                { hebrew: "דבורה", foreign: "abeja" },
                { hebrew: "פרפר", foreign: "mariposa" },
                { hebrew: "זבוב", foreign: "mosca" },
                { hebrew: "יתוש", foreign: "mosquito" }
            ]
        },
        {
            level: 6,
            name: "רמה 6: אוכל ושתיה",
            words: [
                { hebrew: "מים", foreign: "agua" },
                { hebrew: "לחם", foreign: "pan" },
                { hebrew: "חלב", foreign: "leche" },
                { hebrew: "ביצה", foreign: "huevo" },
                { hebrew: "תפוח", foreign: "manzana" },
                { hebrew: "בננה", foreign: "plátano" },
                { hebrew: "עגבניה", foreign: "tomate" },
                { hebrew: "גבינה", foreign: "queso" },
                { hebrew: "בשר", foreign: "carne" },
                { hebrew: "דג", foreign: "pescado" },
                { hebrew: "פירות", foreign: "frutas" },
                { hebrew: "ירקות", foreign: "verduras" },
                { hebrew: "אורז", foreign: "arroz" },
                { hebrew: "פסטה", foreign: "pasta" },
                { hebrew: "תפוח אדמה", foreign: "patata" },
                { hebrew: "בצל", foreign: "cebolla" },
                { hebrew: "שום", foreign: "ajo" },
                { hebrew: "מלח", foreign: "sal" },
                { hebrew: "פלפל", foreign: "pimienta" },
                { hebrew: "שמן", foreign: "aceite" },
                { hebrew: "חומץ", foreign: "vinagre" },
                { hebrew: "סוכר", foreign: "azúcar" },
                { hebrew: "קפה", foreign: "café" },
                { hebrew: "תה", foreign: "té" },
                { hebrew: "מיץ", foreign: "zumo" },
                { hebrew: "בירה", foreign: "cerveza" },
                { hebrew: "יין", foreign: "vino" },
                { hebrew: "לחמניה", foreign: "panecillo" },
                { hebrew: "עוגה", foreign: "pastel" },
                { hebrew: "גלידה", foreign: "helado" },
                { hebrew: "שוקולד", foreign: "chocolate" },
                { hebrew: "ממתק", foreign: "dulce" },
                { hebrew: "משקאות", foreign: "bebidas" },
                { hebrew: "אוכל", foreign: "comida" }
            ]
        },
        {
            level: 7,
            name: "רמה 7: פעלים",
            words: [
                { hebrew: "אכילה", foreign: "comer" },
                { hebrew: "שתייה", foreign: "beber" },
                { hebrew: "שינה", foreign: "dormir" },
                { hebrew: "הליכה", foreign: "caminar" },
                { hebrew: "ריצה", foreign: "correr" },
                { hebrew: "קפיצה", foreign: "saltar" },
                { hebrew: "שחייה", foreign: "nadar" },
                { hebrew: "רכיבה", foreign: "montar" },
                { hebrew: "נסיעה", foreign: "viajar" },
                { hebrew: "עבודה", foreign: "trabajar" },
                { hebrew: "לימודים", foreign: "estudiar" },
                { hebrew: "משחק", foreign: "jugar" },
                { hebrew: "שירה", foreign: "cantar" },
                { hebrew: "ריקוד", foreign: "bailar" },
                { hebrew: "ציור", foreign: "dibujar" },
                { hebrew: "כתיבה", foreign: "escribir" },
                { hebrew: "קריאה", foreign: "leer" },
                { hebrew: "דיבור", foreign: "hablar" },
                { hebrew: "שמיעה", foreign: "escuchar" },
                { hebrew: "ראייה", foreign: "ver" },
                { hebrew: "ריח", foreign: "oler" },
                { hebrew: "מגע", foreign: "tocar" },
                { hebrew: "רגש", foreign: "sentir" },
                { hebrew: "מחשבה", foreign: "pensar" },
                { hebrew: "זיכרון", foreign: "recordar" },
                { hebrew: "שכחה", foreign: "olvidar" },
                { hebrew: "למידה", foreign: "aprender" },
                { hebrew: "נהיגה", foreign: "conducir" },
                { hebrew: "טיסה", foreign: "volar" },
                { hebrew: "עלייה", foreign: "subir" },
                { hebrew: "ירידה", foreign: "bajar" },
                { hebrew: "כניסה", foreign: "entrar" },
                { hebrew: "יציאה", foreign: "salir" },
                { hebrew: "עצירה", foreign: "parar" },
                { hebrew: "התחלה", foreign: "empezar" },
                { hebrew: "סיום", foreign: "terminar" },
                { hebrew: "פתיחה", foreign: "abrir" },
                { hebrew: "סגירה", foreign: "cerrar" },
                { hebrew: "חיפוש", foreign: "buscar" },
                { hebrew: "מציאה", foreign: "encontrar" },
                { hebrew: "הפסד", foreign: "perder" },
                { hebrew: "זכייה", foreign: "ganar" },
                { hebrew: "שכיבה", foreign: "acostarse" },
                { hebrew: "קימה", foreign: "levantarse" },
                { hebrew: "ישיבה", foreign: "sentarse" },
                { hebrew: "עמידה", foreign: "pararse" },
                { hebrew: "טיול", foreign: "pasear" }
            ]
        },
        {
            level: 8,
            name: "רמה 8: שמות תואר",
            words: [
                { hebrew: "טוב", foreign: "bueno" },
                { hebrew: "רע", foreign: "malo" },
                { hebrew: "יפה", foreign: "hermoso" },
                { hebrew: "מכוער", foreign: "feo" },
                { hebrew: "גדול", foreign: "grande" },
                { hebrew: "קטן", foreign: "pequeño" },
                { hebrew: "ארוך", foreign: "largo" },
                { hebrew: "קצר", foreign: "corto" },
                { hebrew: "רחב", foreign: "ancho" },
                { hebrew: "צר", foreign: "estrecho" },
                { hebrew: "גבוה", foreign: "alto" },
                { hebrew: "נמוך", foreign: "bajo" },
                { hebrew: "כבד", foreign: "pesado" },
                { hebrew: "קל", foreign: "ligero" },
                { hebrew: "חם", foreign: "caliente" },
                { hebrew: "קר", foreign: "frío" },
                { hebrew: "מתוק", foreign: "dulce" },
                { hebrew: "מר", foreign: "amargo" },
                { hebrew: "חמוץ", foreign: "ácido" },
                { hebrew: "מלוח", foreign: "salado" },
                { hebrew: "חריף", foreign: "picante" },
                { hebrew: "רך", foreign: "suave" },
                { hebrew: "קשה", foreign: "duro" },
                { hebrew: "יבש", foreign: "seco" },
                { hebrew: "רטוב", foreign: "mojado" },
                { hebrew: "נקי", foreign: "limpio" },
                { hebrew: "מלוכלך", foreign: "sucio" },
                { hebrew: "חדש", foreign: "nuevo" },
                { hebrew: "ישן", foreign: "viejo" },
                { hebrew: "צעיר", foreign: "joven" },
                { hebrew: "בריא", foreign: "sano" },
                { hebrew: "חולה", foreign: "enfermo" },
                { hebrew: "חזק", foreign: "fuerte" },
                { hebrew: "חלש", foreign: "débil" },
                { hebrew: "מהיר", foreign: "rápido" },
                { hebrew: "איטי", foreign: "lento" },
                { hebrew: "יקר", foreign: "caro" },
                { hebrew: "זול", foreign: "barato" },
                { hebrew: "ריק", foreign: "vacío" },
                { hebrew: "מלא", foreign: "lleno" },
                { hebrew: "פתוח", foreign: "abierto" },
                { hebrew: "סגור", foreign: "cerrado" },
                { hebrew: "חופשי", foreign: "libre" },
                { hebrew: "עסוק", foreign: "ocupado" },
                { hebrew: "שקט", foreign: "tranquilo" },
                { hebrew: "רועש", foreign: "ruidoso" },
                { hebrew: "בהיר", foreign: "claro" },
                { hebrew: "כהה", foreign: "oscuro" }
            ]
        },
        {
            level: 9,
            name: "רמה 9: בגדים",
            words: [
                { hebrew: "כובע", foreign: "sombrero" },
                { hebrew: "חולצה", foreign: "camisa" },
                { hebrew: "מכנסיים", foreign: "pantalones" },
                { hebrew: "נעליים", foreign: "zapatos" },
                { hebrew: "גרביים", foreign: "calcetines" },
                { hebrew: "תיק", foreign: "bolso" },
                { hebrew: "ארנק", foreign: "cartera" },
                { hebrew: "משקפיים", foreign: "gafas" },
                { hebrew: "שמלה", foreign: "vestido" },
                { hebrew: "מעיל", foreign: "abrigo" }
            ]
        },
        {
            level: 10,
            name: "רמה 10: חלקי גוף",
            words: [
                { hebrew: "ראש", foreign: "cabeza" },
                { hebrew: "יד", foreign: "mano" },
                { hebrew: "רגל", foreign: "pie" },
                { hebrew: "עין", foreign: "ojo" },
                { hebrew: "אוזן", foreign: "oído" },
                { hebrew: "אף", foreign: "nariz" },
                { hebrew: "פה", foreign: "boca" },
                { hebrew: "שיער", foreign: "pelo" },
                { hebrew: "אצבע", foreign: "dedo" },
                { hebrew: "גוף", foreign: "cuerpo" }
            ]
        },
        {
            level: 11,
            name: "רמה 11: הבית",
            words: [
                { hebrew: "בית", foreign: "casa" },
                { hebrew: "חדר", foreign: "habitación" },
                { hebrew: "שולחן", foreign: "mesa" },
                { hebrew: "כיסא", foreign: "silla" },
                { hebrew: "חלון", foreign: "ventana" },
                { hebrew: "דלת", foreign: "puerta" },
                { hebrew: "אור", foreign: "luz" },
                { hebrew: "חושך", foreign: "oscuridad" },
                { hebrew: "מפתח", foreign: "llave" },
                { hebrew: "מקרר", foreign: "nevera" },
                { hebrew: "תנור", foreign: "horno" }
            ]
        },
        {
            level: 12,
            name: "רמה 12: עיר ותחבורה",
            words: [
                { hebrew: "רכבת", foreign: "tren" },
                { hebrew: "סירה", foreign: "barco" },
                { hebrew: "מונית", foreign: "taxi" },
                { hebrew: "אופניים", foreign: "bicicleta" },
                { hebrew: "קטנוע", foreign: "moto" },
                { hebrew: "רכב", foreign: "coche" },
                { hebrew: "כביש", foreign: "carretera" },
                { hebrew: "תחנה", foreign: "estación" },
                { hebrew: "שדה תעופה", foreign: "aeropuerto" },
                { hebrew: "נמל", foreign: "puerto" }
            ]
        },
        {
            level: 13,
            name: "רמה 13: טכנולוגיה",
            words: [
                { hebrew: "מחשב", foreign: "ordenador" },
                { hebrew: "טלפון", foreign: "teléfono" },
                { hebrew: "טלוויזיה", foreign: "televisión" },
                { hebrew: "רדיו", foreign: "radio" },
                { hebrew: "שעון", foreign: "reloj" },
                { hebrew: "מצלם", foreign: "fotógrafo" }
            ]
        },
        {
            level: 14,
            name: "רמה 14: טבע",
            words: [
                { hebrew: "יום", foreign: "día" },
                { hebrew: "לילה", foreign: "noche" },
                { hebrew: "שמש", foreign: "sol" },
                { hebrew: "ירח", foreign: "luna" },
                { hebrew: "כוכב", foreign: "estrella" },
                { hebrew: "שמים", foreign: "cielo" },
                { hebrew: "ארץ", foreign: "tierra" },
                { hebrew: "ים", foreign: "mar" },
                { hebrew: "נהר", foreign: "río" },
                { hebrew: "אגם", foreign: "lago" },
                { hebrew: "יער", foreign: "bosque" },
                { hebrew: "פרח", foreign: "flor" },
                { hebrew: "עץ", foreign: "árbol" },
                { hebrew: "עלה", foreign: "hoja" }
            ]
        },
        {
            level: 15,
            name: "רמה 15: מושגים",
            words: [
                { hebrew: "הוראה", foreign: "enseñar" },
                { hebrew: "עזרה", foreign: "ayudar" },
                { hebrew: "בקשה", foreign: "pedir" },
                { hebrew: "תשובה", foreign: "responder" },
                { hebrew: "שאלה", foreign: "preguntar" },
                { hebrew: "הסבר", foreign: "explicar" },
                { hebrew: "הבנה", foreign: "entender" },
                { hebrew: "סכמה", foreign: "acuerdo" },
                { hebrew: "אהבה", foreign: "amor" },
                { hebrew: "שנאה", foreign: "odio" },
                { hebrew: "שמחה", foreign: "alegría" },
                { hebrew: "עצב", foreign: "tristeza" },
                { hebrew: "כעס", foreign: "enojo" },
                { hebrew: "פחד", foreign: "miedo" },
                { hebrew: "הפתעה", foreign: "sorpresa" },
                { hebrew: "בושה", foreign: "vergüenza" },
                { hebrew: "גאווה", foreign: "orgullo" },
                { hebrew: "קנאה", foreign: "envidia" },
                { hebrew: "אכזבה", foreign: "decepción" },
                { hebrew: "תקווה", foreign: "esperanza" },
                { hebrew: "חלום", foreign: "sueño" },
                { hebrew: "מציאות", foreign: "realidad" },
                { hebrew: "אמת", foreign: "verdad" },
                { hebrew: "שקר", foreign: "mentira" }
            ]
        },
        {
            level: 16,
            name: "רמה 16: מקצועות",
            words: [
                { hebrew: "רופא", foreign: "médico" },
                { hebrew: "אחות (רפואית)", foreign: "enfermera" },
                { hebrew: "מורה", foreign: "maestro" },
                { hebrew: "נהג", foreign: "conductor" },
                { hebrew: "כבאי", foreign: "bombero" },
                { hebrew: "שוטר", foreign: "policía" },
                { hebrew: "חייל", foreign: "soldado" },
                { hebrew: "מהנדס", foreign: "ingeniero" },
                { hebrew: "אדריכל", foreign: "arquitecto" },
                { hebrew: "חקלאי", foreign: "agricultor" },
                { hebrew: "טבח", foreign: "cocinero" },
                { hebrew: "מלצר", foreign: "camarero" },
                { hebrew: "מוכרת", foreign: "vendedora" },
                { hebrew: "פקיד", foreign: "oficinista" },
                { hebrew: "מנהל", foreign: "gerente" },
                { hebrew: "שחקן", foreign: "actor" },
                { hebrew: "זמר", foreign: "cantante" },
                { hebrew: "רקדן", foreign: "bailarín" },
                { hebrew: "טייס", foreign: "piloto" },
                { hebrew: "קברניט", foreign: "capitán" },
                { hebrew: "נגר", foreign: "carpintero" },
                { hebrew: "חשמלאי", foreign: "electricista" },
                { hebrew: "שרברב", foreign: "fontanero" },
                { hebrew: "טכנאי", foreign: "técnico" },
                { hebrew: "אומן", foreign: "artesano" },
                { hebrew: "סופר", foreign: "escritor" },
                { hebrew: "צייר", foreign: "pintor" },
                { hebrew: "עיתונאי", foreign: "periodista" },
                { hebrew: "חוקר", foreign: "investigador" }
            ]
        },
        {
            level: 17,
            name: "רמה 17: כלכלה",
            words: [
                { hebrew: "חוב", foreign: "deuda" },
                { hebrew: "השקעה", foreign: "inversión" },
                { hebrew: "רווח", foreign: "ganancia" },
                { hebrew: "הפסד", foreign: "pérdida" },
                { hebrew: "שוק", foreign: "mercado" },
                { hebrew: "מניה", foreign: "acción" },
                { hebrew: "ביטוח", foreign: "seguro" },
                { hebrew: "משכנתא", foreign: "hipoteca" },
                { hebrew: "בנק", foreign: "banco" },
                { hebrew: "כרטיס אשראי", foreign: "tarjeta de crédito" },
                { hebrew: "חשבון", foreign: "cuenta" },
                { hebrew: "כספומט", foreign: "cajero automático" },
                { hebrew: "הלוואה", foreign: "préstamo" },
                { hebrew: "עמלה", foreign: "comisión" },
                { hebrew: "משכורת", foreign: "sueldo" },
                { hebrew: "הכנסה", foreign: "ingreso" },
                { hebrew: "הוצאה", foreign: "gasto" },
                { hebrew: "תקציב", foreign: "presupuesto" },
                { hebrew: "חיסכון", foreign: "ahorro" },
                { hebrew: "קנס", foreign: "multa" }
            ]
        },
        {
            level: 18,
            name: "רמה 18: כלי מטבח",
            words: [
                { hebrew: "מזלג", foreign: "tenedor" },
                { hebrew: "סכין", foreign: "cuchillo" },
                { hebrew: "כף", foreign: "cuchara" },
                { hebrew: "צלחת", foreign: "plato" },
                { hebrew: "כוס", foreign: "vaso" },
                { hebrew: "קערה", foreign: "tazón" },
                { hebrew: "מפית", foreign: "servilleta" }
            ]
        }
    ]
};
